source 'https://rubygems.org'

gem "rails", "~> 8.1"

gem "bootsnap", "~> 1.24"

gem "puma", "~> 8.0"

gem "docker-api", "~> 2.4"
gem "pg", "~> 1.4"

gem "rack-cors", "~> 3.0"

gem "thruster", "~> 0.1.21"
